version: '3'

services:

  # Postgres
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile.postgres
    environment:
      - POSTGRES_USER=web
      - POSTGRES_PASSWORD=web
      - POSTGRES_DB=web
    ports:
      - ${POSTGRES_PORT_TO_EXPOSE}:5432
    volumes:
      - postgresql_volume:/var/lib/postgresql/data

  # NGINX proxy for virtual hosts inside docker
  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile.nginx
    ports:
      - ${NGINX_PORT_TO_EXPOSE}:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # PgAdmin
  pgadmin:
    build:
      context: services/pgadmin
      dockerfile: Dockerfile.pgadmin
    environment:
      - VIRTUAL_HOST=pgadmin.postgres.local
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=root@localhost
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
      - pgadmin_volume:/servers.json
      - pgadmin_volume:/pgadmin4/config_local.py
      - pgadmin_volume:/pgadmin4/servers.json

  # PHP
  phpapp:
    build:
      context: services/phpapp
      dockerfile: Dockerfile.phpapp
    volumes:
      -  ${SYMFONY_APP_PATH}:/code/
    environment:
      - VIRTUAL_HOST=phpapp.postgres.local
      - APP_ENV=dev
      - COMPOSER_CACHE_DIR=/tmp
      - COMPOSER_ALLOW_SUPERUSER=1
      - SYMFONY_CACHE_DIR=${SYMFONY_CACHE_DIR}

volumes:
  postgresql_volume:
  pgadmin_volume: