version: '3'

services:

  # Postgres
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile.postgres
    environment:
      - POSTGRES_USER=web
      - POSTGRES_PASSWORD=web
      - POSTGRES_DB=web
    ports:
      - ${POSTGRES_PORT_TO_EXPOSE}:5432
    volumes:
      - postgresql_volume:/var/lib/postgresql/data

  # PgAdmin
  pgadmin:
    build:
      context: services/pgadmin
      dockerfile: Dockerfile.pgadmin
    environment:
      - VIRTUAL_HOST=varlib.postgres.local
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=root@localhost
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 80:80
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
      - pgadmin_volume:/servers.json
      - pgadmin_volume:/pgadmin4/config_local.py
      - pgadmin_volume:/pgadmin4/servers.json

volumes:
  postgresql_volume:
  pgadmin_volume: